/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author caes2
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        OP_Datos = new javax.swing.JMenu();
        OP_Paciente = new javax.swing.JMenuItem();
        OP_Medico = new javax.swing.JMenuItem();
        OP_Recepcionista = new javax.swing.JMenuItem();
        OP_Reservas = new javax.swing.JMenu();
        OP_Citas = new javax.swing.JMenuItem();
        OP_Informe = new javax.swing.JMenu();
        Consultar_historial_del_paciente = new javax.swing.JMenuItem();
        OP_Consultar_Citas = new javax.swing.JMenu();
        OP_ConCitas_todosLosPacientes = new javax.swing.JMenuItem();
        OP_ConCitas_PorMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        OP_Datos.setText("Datos");

        OP_Paciente.setText("Paciente");
        OP_Datos.add(OP_Paciente);

        OP_Medico.setText("Medico");
        OP_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_MedicoActionPerformed(evt);
            }
        });
        OP_Datos.add(OP_Medico);

        OP_Recepcionista.setText("Recepcionista");
        OP_Recepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_RecepcionistaActionPerformed(evt);
            }
        });
        OP_Datos.add(OP_Recepcionista);

        jMenuBar1.add(OP_Datos);

        OP_Reservas.setText("Reservas");
        OP_Reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_ReservasActionPerformed(evt);
            }
        });

        OP_Citas.setText("Citas");
        OP_Citas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OP_Citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_CitasActionPerformed(evt);
            }
        });
        OP_Reservas.add(OP_Citas);

        jMenuBar1.add(OP_Reservas);

        OP_Informe.setText("Informe");

        Consultar_historial_del_paciente.setText("Consultar historial del paciente");
        Consultar_historial_del_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_historial_del_pacienteActionPerformed(evt);
            }
        });
        OP_Informe.add(Consultar_historial_del_paciente);

        OP_Consultar_Citas.setText("Consultar citas");

        OP_ConCitas_todosLosPacientes.setText("Todos los pacientes");
        OP_ConCitas_todosLosPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_ConCitas_todosLosPacientesActionPerformed(evt);
            }
        });
        OP_Consultar_Citas.add(OP_ConCitas_todosLosPacientes);

        OP_ConCitas_PorMedico.setText("Por medico");
        OP_ConCitas_PorMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_ConCitas_PorMedicoActionPerformed(evt);
            }
        });
        OP_Consultar_Citas.add(OP_ConCitas_PorMedico);

        OP_Informe.add(OP_Consultar_Citas);

        jMenuBar1.add(OP_Informe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        setBounds(0, 0, 570, 228);
    }// </editor-fold>//GEN-END:initComponents

    private void OP_ReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_ReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_ReservasActionPerformed

    private void OP_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_MedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_MedicoActionPerformed

    private void OP_RecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_RecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_RecepcionistaActionPerformed

    private void Consultar_historial_del_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_historial_del_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Consultar_historial_del_pacienteActionPerformed

    private void OP_CitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_CitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_CitasActionPerformed

    private void OP_ConCitas_todosLosPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_ConCitas_todosLosPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_ConCitas_todosLosPacientesActionPerformed

    private void OP_ConCitas_PorMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_ConCitas_PorMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_ConCitas_PorMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem Consultar_historial_del_paciente;
    public javax.swing.JMenuItem OP_Citas;
    public javax.swing.JMenuItem OP_ConCitas_PorMedico;
    public javax.swing.JMenuItem OP_ConCitas_todosLosPacientes;
    public javax.swing.JMenu OP_Consultar_Citas;
    private javax.swing.JMenu OP_Datos;
    private javax.swing.JMenu OP_Informe;
    public javax.swing.JMenuItem OP_Medico;
    public javax.swing.JMenuItem OP_Paciente;
    public javax.swing.JMenuItem OP_Recepcionista;
    public javax.swing.JMenu OP_Reservas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
